---- Base app schema

-- User
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    typ user_typ NOT NULL DEFAULT 'User',
    username VARCHAR(128) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,

    -- Auth
    pwd VARCHAR(256),
    pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
    token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

    -- Email verification
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verification_token VARCHAR(255),
    email_verification_expires_at TIMESTAMPTZ,

     -- Timestamps
    cid BIGINT NOT NULL REFERENCES "user"(id),
    ctime TIMESTAMPTZ NOT NULL DEFAULT now(),
    mid BIGINT NOT NULL REFERENCES "user"(id),
    mtime TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Post
CREATE TABLE post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    description TEXT NOT NULL,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit fields
    cid BIGINT NOT NULL REFERENCES "user"(id),
    ctime TIMESTAMPTZ NOT NULL DEFAULT now(),
    mid BIGINT NOT NULL REFERENCES "user"(id), 
    mtime TIMESTAMPTZ NOT NULL DEFAULT now()
);