---- Base app schema

-- User
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    typ user_typ NOT NULL DEFAULT 'User',
    username VARCHAR(128) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    avatar_url TEXT,
    bio TEXT,
    location TEXT,

    -- Auth
    pwd VARCHAR(256),
    pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),

    -- Token
    token_salt UUID NOT NULL DEFAULT gen_random_uuid(),
    reset_token TEXT,
    reset_token_expires_at TIMESTAMPTZ,

    -- Email verification
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verification_token VARCHAR(255),
    email_verification_expires_at TIMESTAMPTZ,

     -- Timestamps
    cid BIGINT NOT NULL REFERENCES "user"(id),
    ctime TIMESTAMPTZ NOT NULL DEFAULT now(),
    mid BIGINT NOT NULL REFERENCES "user"(id),
    mtime TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Followers & Followings
CREATE TABLE user_follow (
    follower_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    following_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (follower_id, following_id)
);

-- Stats
CREATE TABLE user_stats (
    user_id BIGINT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
    posts_count BIGINT NOT NULL DEFAULT 0,
    followers_count BIGINT NOT NULL DEFAULT 0,
    following_count BIGINT NOT NULL DEFAULT 0
);

-- Post
CREATE TABLE post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    
    -- Core fields
    user_id BIGINT NOT NULL REFERENCES "user"(id),
    title VARCHAR(256) NOT NULL,
    description TEXT NOT NULL,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,

    -- Media metadata
    cover_media_url TEXT,
    thumbnail_url TEXT,
    media_count INT NOT NULL DEFAULT 0,
    has_video BOOLEAN NOT NULL DEFAULT FALSE,

    -- Stats
    like_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    saved_count BIGINT NOT NULL DEFAULT 0,

    -- Audit fields
    cid BIGINT NOT NULL REFERENCES "user"(id),
    ctime TIMESTAMPTZ NOT NULL DEFAULT now(),
    mid BIGINT NOT NULL REFERENCES "user"(id),
    mtime TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- PostMedia
CREATE TABLE post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES post(id) ON DELETE CASCADE,

    media_url TEXT NOT NULL,
    media_type VARCHAR(16) NOT NULL,       -- "image" | "video"
    mime_type VARCHAR(128) NOT NULL,

    width INT,
    height INT,
    file_size BIGINT,
    duration INT,                          -- seconds for video
    sort_order INT NOT NULL DEFAULT 0,

    -- Audit fields
    cid BIGINT NOT NULL REFERENCES "user"(id),
    ctime TIMESTAMPTZ NOT NULL DEFAULT now(),
    mid BIGINT NOT NULL REFERENCES "user"(id), 
    mtime TIMESTAMPTZ NOT NULL DEFAULT now()
);
